name: code_forge_web
description: "The web version of the powerful code_forge package"
version: 2.8.0
homepage: https://github.com/heckmon/code_forge_web

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  http: ^1.2.2
  markdown_widget: ^2.3.2+8
  re_highlight: ^0.0.3
  vector_math: ^2.2.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: Method
      fonts:
        - asset: assets/icons/method.ttf
    - family: Variable
      fonts:
        - asset: assets/icons/variable.ttf
    - family: Class
      fonts:
        - asset: assets/icons/class.ttf
    - family: Reference
      fonts:
        - asset: assets/icons/reference.ttf
    - family: Struct
      fonts:
        - asset: assets/icons/struct.ttf
    - family: Event
      fonts:
        - asset: assets/icons/event.ttf
    - family: Operator
      fonts:
        - asset: assets/icons/operator.ttf
    - family: Parameter
      fonts:
        - asset: assets/icons/parameter.ttf
    - family: Interface
      fonts:
        - asset: assets/icons/interface.ttf
    - family: Field
      fonts:
        - asset: assets/icons/field.ttf
